package hospital

import (
	"time"

	"github.com/google/uuid"
)

type Status string

const (
	StatusPending  Status = "PENDING"
	StatusVerified Status = "VERIFIED"
	StatusActive   Status = "ACTIVE"
	StatusInactive Status = "INACTIVE"
)

type Hospital struct {
	ID                 uuid.UUID  `json:"id"`
	Name               string     `json:"name"`
	Address            string     `json:"address"`
	Phone              string     `json:"phone"`
	Email              string     `json:"email"`
	RegistrationNumber string     `json:"registrationNumber"`
	NPWP               string     `json:"npwp,omitempty"`
	LicenseDocumentURL string     `json:"licenseDocumentUrl,omitempty"`
	PICUserID          *uuid.UUID `json:"picUserId,omitempty"`
	Status             Status     `json:"status"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

type Staff struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"userId"`
	HospitalID uuid.UUID `json:"hospitalId"`
	FullName   string    `json:"fullName"`
	Position   string    `json:"position"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// Invitation represents a one-time registration key and magic link
// generated by an Admin for prospective hospital representatives.
type Invitation struct {
	ID          uuid.UUID  `json:"id"`
	KeyCode     string     `json:"keyCode"`
	TargetEmail string     `json:"targetEmail"`
	CreatedBy   uuid.UUID  `json:"createdBy"`
	UsedBy      *uuid.UUID `json:"usedBy,omitempty"`
	IsUsed      bool       `json:"isUsed"`
	ExpiresAt   time.Time  `json:"expiresAt"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

func (i *Invitation) IsExpired() bool {
	return time.Now().After(i.ExpiresAt)
}

type ApplicationStatus string

const (
	ApplicationPendingReview    ApplicationStatus = "PENDING_REVIEW"
	ApplicationRevisionRequired ApplicationStatus = "REVISION_REQUIRED"
	ApplicationRejected         ApplicationStatus = "REJECTED"
	ApplicationApproved         ApplicationStatus = "APPROVED"
)

func (s ApplicationStatus) IsValid() bool {
	switch s {
	case ApplicationPendingReview, ApplicationRevisionRequired, ApplicationRejected, ApplicationApproved:
		return true
	}
	return false
}

type HospitalApplication struct {
	ID                 uuid.UUID         `json:"id"`
	InvitationID       uuid.UUID         `json:"invitationId"`
	ApplicantUserID    uuid.UUID         `json:"applicantUserId"`
	Name               string            `json:"name"`
	Address            string            `json:"address"`
	Phone              string            `json:"phone"`
	Email              string            `json:"email"`
	RegistrationNumber string            `json:"registrationNumber"`
	NPWP               string            `json:"npwp,omitempty"`
	LicenseDocumentURL string            `json:"licenseDocumentUrl,omitempty"`
	PICFullName        string            `json:"picFullName"`
	PICPosition        string            `json:"picPosition"`
	Status             ApplicationStatus `json:"status"`
	AdminNotes         string            `json:"adminNotes,omitempty"`
	CreatedAt          time.Time         `json:"createdAt"`
	UpdatedAt          time.Time         `json:"updatedAt"`
}
